Audit mode with default true
kubecost/disk-autoscaler pull request #21
Opened 2024-05-16 22:07 UTC by avrodrigues5

## What does this PR change?
Introduces audit mode run for Disk auto scaler

## Does this PR rely on any other PRs?
None

## How does this PR impact users?
Default will be audit mode, unless it set to false the Disk auto scaling wouldnt perform any scaling up and scaling down operations

## Links to Issues or tickets this PR addresses or fixes
closes #4 

## What risks are associated with merging this PR? What is required to fully test this PR?

The audit mode is a safe option as default so its better for user

## How was this PR tested?
When run in audit mode
![Screenshot 2024-05-15 at 7 04 27 PM](https://github.com/kubecost/disk-autoscaler/assets/11470561/aa7f6cc5-24ab-437d-ae39-0fd4a744a282)

Without audit mode tested for scale up and scale down operation

2024-05-16 22:16 UTC, chipzoller requested changes
Can you please copy that logged output in audit mode as a code block, not screenshot? We should add this to the README.

2024-05-16 22:54 UTC, avrodrigues5 commented
> Can you please copy that logged output in audit mode as a code block, not screenshot? We should add this to the README.

Done

2024-05-16 23:42 UTC, chipzoller commented on pkg/diskscaler/diskscaler.go
> +	// No further action is needed if its audit mode
```suggestion
	// No further action is needed if audit mode is enabled
```

2024-05-16 23:43 UTC, chipzoller commented on pkg/diskscaler/diskscaler.go
> +			// The PV claim name is required even thou it's audit mode so we continue and not provide any recommendation or err logs
```suggestion
			// The PVC name is required even when in audit mode so we continue and don't provide any recommendation or err logs
```

2024-05-16 23:44 UTC, chipzoller commented on pkg/diskscaler/diskscaler.go
> +			// this condition is typical encountered when we have ephemeral storage. i.e storage tied to pod lifecyle.
```suggestion
			// this condition is typically encountered when we have ephemeral storage, i.e storage tied to pod lifecyle.
```

2024-05-16 23:44 UTC, chipzoller commented on pkg/diskscaler/diskscaler.go
> +			// The PVC information is required even thou it's audit mode so we continue and not provide any recommendation or err logs
```suggestion
			// The PVC information is required even when in audit mode so we continue and don't provide any recommendations or err logs
```

2024-05-16 23:50 UTC, chipzoller commented on pkg/diskscaler/diskscaler.go
> +		// CHeck to see if pv is not hostpath mounted, Kubecost doesnt provide recommendation to hostpath mounts at this time.
```suggestion
		// Check to see if PV is not hostPath mounted. Kubecost doesn't provide recommendations for hostPath mounts at this time.
```

2024-05-16 23:52 UTC, chipzoller approved these changes

2024-05-16 23:52 UTC, chipzoller commented
@avrodrigues5 please review latest README changes.

2024-05-16 23:55 UTC, merged

2024-05-17 15:55 UTC, dwbrown2 commented
Really cool! Just a future idea, could be nice to show % savings and maybe even a total expected savings amount.